services:
  backend:
    build:
      context: ./Back-End
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Database=peopleDB;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db
    #networks:
      #- app_network

  frontend:
    build:
      context: ./Front-End
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    #networks:
      #- app_network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    command: /opt/mssql/bin/sqlservr
    #networks:
      #- app_network

volumes:
  sqlserver_data:
#networks:
  #app_network:
      #driver: bridge