name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./Back-End/Back-End.csproj

    - name: Build
      run: dotnet build ./Back-End/Back-End.csproj --no-restore

    - name: Test
      run: dotnet test ./Back-End/Back-End.csproj --no-build --verbosity normal

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci
      working-directory: ./Front-End

    - name: Run tests
      run: npm test
      working-directory: ./Front-End

  build-and-push-images:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./Back-End
        push: true
        tags: abdelkarim246/internship-back:latest

    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./Front-End
        push: true
        tags: abdelkarim246/internship-front:latest

  deploy:
    needs: build-and-push-images
    runs-on: ubuntu-latest
    
    steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Restart backend container app
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az containerapp restart --name myapp-back --resource-group internship-group

    - name: Restart frontend container app
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az containerapp restart --name myapp-front --resource-group internship-group
