
name: Build and Deploy to Azure via Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push frontend image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: ./Front-End
        push: true
        tags: abdelkarim246/internship-front:latest,abdelkarim246/internship-front:${{ github.sha }}
    
    - name: Build and push backend image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: ./Back-End
        push: true
        tags: abdelkarim246/internship-back:latest,abdelkarim246/internship-back:${{ github.sha }}
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy Frontend to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}/Front-End
        containerAppName: ${{ secrets.AZURE_CONTAINER_APP_FRONTEND_NAME }}
        resourceGroup: NeoLedge-Internship
        imageToDeploy: abdelkarim246/internship-front:${{ github.sha }}
    
    - name: Deploy Backend to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}/Back-End
        containerAppName: ${{ secrets.AZURE_CONTAINER_APP_BACKEND_NAME }}
        resourceGroup: NeoLedge-Internship
        imageToDeploy: abdelkarim246/internship-back:${{ github.sha }}
